---
- name: Clone Laravel repository
  git:
    repo: 'git@github.com:abettie/multibook-backend.git'
    dest: /var/www/api
    version: master
    accept_hostkey: yes

- name: Copy .env file
  template:
    src: env.j2
    dest: /var/www/api/.env
    mode: 0600
    force: yes

- name: Install composer dependencies
  command: composer install --no-interaction --prefer-dist
  args:
    chdir: /var/www/api

- name: Install npm dependencies
  command: npm install
  args:
    chdir: /var/www/api

- name: Build assets
  command: npm run build
  args:
    chdir: /var/www/api

- name: Run database migrations
  command: php artisan migrate --force
  args:
    chdir: /var/www/api
