---
- name: Install MariaDB
  yum:
    name:
      - mariadb-server
      - MySQL-python
    state: present

- name: Ensure MariaDB is running
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Set MariaDB character set to utf8mb4
  lineinfile:
    path: /etc/my.cnf.d/server.cnf
    regexp: '^character-set-server'
    line: 'character-set-server=utf8mb4'
    insertafter: '[mysqld]'
  notify: Restart mariadb

- name: Create database
  mysql_db:
    name: "{{ laravel_db_name }}"
    encoding: utf8mb4
    collation: utf8mb4_unicode_ci
    state: present

- name: Create database user
  mysql_user:
    name: "{{ laravel_db_user }}"
    password: "{{ laravel_db_password }}"
    priv: "{{ laravel_db_name }}.*:ALL"
    host: "%"
    state: present

handlers:
  - name: Restart mariadb
    service:
      name: mariadb
      state: restarted
