---
- name: Set timezone to Asia/Tokyo
  community.general.timezone:
    name: Asia/Tokyo

- name: Confirm system locale
  ansible.builtin.command: localectl status
  register: localectl_result
  check_mode: false
  changed_when: false

- name: Set system locale to ja_JP.utf8
  ansible.builtin.command: localectl set-locale LANG=ja_JP.utf8
  when: "'LANG=ja_JP.utf8' not in localectl_result.stdout"

- name: set LANG=ja_JP.UTF-8 in /etc/sysconfig/i18n
  lineinfile:
    dest: /etc/sysconfig/i18n
    regexp: "^LANG="
    line: "LANG=ja_JP.UTF-8"

- name: Install packages
  ansible.builtin.dnf:
    name:
      - python3-pip
      - git
      - unzip
      - gcc
      - make
      - nodejs
      - npm
    state: present

- name: Add git aliases to /home/ec2-user/.bashrc
  blockinfile:
    path: /root/.bashrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK: git aliases"
    block: |
      alias glog='git log --date=iso --pretty="format:%C(yellow)%h %C(green)%cd %C(blue)%an%C(red)%d %C(reset)%s" -20 --graph'
      alias gst='git status -s'
      alias gb='git branch'
      alias gc='git checkout'
      alias gr='git stash && git checkout master && git pull origin master && git branch --merged | grep -v "master" | xargs git branch -d && git fetch -p'
  become: true
  become_user: root